### ISSUE TITLE
validation: update self-test subcmd

### ISSUE THREAD

**Issue by pnengchu** [target/goalert#1134]
**Describe the Bug:**
Discovery needed: update the sub-command `goalert self-test` suite with a check on the bundedled `app.js` to make sure the backend version and app version build images match. 

**Expected Behavior:**
build images match and return OK 

**Additional Context:**
ties to issue #1029

**Comment by mastercactapus** [comment]
This may need to be done in cypress, and probably doesn't belong in `self-test`. Maybe better would be a startup/runtime check inside the `web` module (only valid if we have bundled data) that logs an error.

What makes it difficult is the version string (e.g., `v0.25.0` could show up in any number of js dependency comments inside the `app.js` file.

It will show up somewhere in the file as something like: `var a="v0.26.0-334-gbe3d0ed6";e.GOALERT_VERSION=a;`

One approach could be to search for `\bGOALERT_VERSION\s*=\s*(.*)\b` (which could be a string or var) and if it's not a string, search backwards for `$1\s*=\s*(.*)\b` or something like that. Since there's only one place we're assigning it, and it should either be a string directly or a reference to something already defined. Unfortunately, there are a number of ways minifiers could change the code that would break that too..
