### ISSUE TITLE
ui/alert details: add breadcrumbs to previous resources

### ISSUE THREAD

**Issue by Forfold** [target/goalert#1349]
**What problem would you like to solve? Please describe:**
When viewing an individual alert, I often go back and forth between the service/alerts page and the alert I'm viewing. It can be hard to remember which context I'm in (from the alerts page, or a service I was looking at).

**Describe the solution you'd like:**
Breadcrumbs in the toolbar to either the alerts page or the service alerts page, depending on the current context.

**Describe alternatives you've considered:**
N/A

**Additional context:**
Breadcrumbs can be seen in a few parts of the application already, one of them being the alerts list from a service's page:

![Screen Shot 2021-03-23 at 8 30 54 AM](https://user-images.githubusercontent.com/11381794/112173195-95e22f00-8bb2-11eb-8288-1929e37a0553.png)

**Comment by pnengchu** [comment]
After investigating a potential solution to allow easier context switching between services -> alerts -> alert details, a refactor of how we handle routes may be beneficial for the application for long term. Additionally, material UI supports breadcrumbs which we can easily apply to our refactored routes which would be cleaner code overall rather than a temp ui fix.
Resource: https://mui.com/components/breadcrumbs/

**Comment by Forfold** [comment]
We have implemented a pretty decent solution with URQL, and an alert link will now always redirect to its service alert page instead.
