### ISSUE TITLE
proposal: lessen label creation restrictions

### ISSUE THREAD

**Issue by Auchindoun** [target/goalert#141]
**Is your feature request related to a problem? Please describe:**
As it stands a label, when created, requires a key be created, which must have a prefix and a suffix (both at least 3 letters long), divided by a `/`. A value to this key is also required for the label to be created.

I feel this hampers the ability for a user to quickly create a label and start organizing their services as such.

The word _label_ has two definitions:

> 1. A small piece of paper, fabric, plastic, or similar material attached to an object and giving information about it.
> 2. A classifying phrase or name applied to a person or thing, especially one that is inaccurate or restrictive.

By this, what a label should be within GoAlert is a small classifying name attached to a Service that is _less_ restrictive than before.

**Describe the solution you'd like:**
I propose that we allow the key of a label to allow all standard characters, sans prefixes and suffixes. This ensures that existing service labels are not broken, but opens up the label creation process for a better ease of use by our end users.

What this does is allows the existing frameworks remain in place for teams that would like to use the key as their organization identifier, and the value as their team name. However what this will also do is allow teams to utilize labels in a fashion best suited for their needs. For example, a GoAlert service could have a label with a key of "GoAlert" and a value of "Monitor", or similar.

**Out of scope:**
This will also allow, in my opinion, searching and filtering to be simplified. Labels for instance could be searched with a query of `label="Goalert"` which could search across the relevant services for this label. Whether this would an exact match or not could be up for further discussion in a separate issue.

**Comment by mastercactapus** [comment]
I do think it could make sense to loosen the restrictions, as it's proven to be confusing and it's very restrictive for no functional reason. But I don't think we should suggest using the key as an organization/group/team identifier.

I think the key should convey meaning & context, as labels could be used in a lot of different ways and team or user-defined keys should probably contain context (most of the time). 

`TeamName=Foobar` could be one label and `TeamName/Priority=Barbaz` could be another, `TeamName` would be globally recognized and `TeamName/Priority` would be specific to `TeamName`'s use. Using the team's name as a prefix is useful because "priority" may not mean the same thing, or be used in the same way, to every team.

The idea with the slash was to force that context (e.g. `my.team/AppName=Monitor`) but that could easily be a convention, rather than enforced in favor of simplicity. And would make it easier to use IMO. We could also just make the prefix optional and leave everything else as-is (which is what k8s does), not super sure on the best route there.

---

The current implementation largely came from Kubernetes' use of labels and selectors for grouping/finding/operating-on resources together, which still aligns well with GoAlert's use case:
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

--- 

As far as character set, I would suggest we follow the restrictions identified above ^ -- which would make the prefix optional but still restrict things like spaces (in keys) that could complicate things like API use or search-query syntax. I'm not sure if Kubernetes has any restrictions on label values, but GoAlert currently allows any printable character and only restricts keys anyhow.

**Comment by Auchindoun** [comment]
Isn't that what the key is for, though? I'm not sure I follow. I was under the impression that the key serves as an identifier to either the org a team is in, or a top level organizer for multiple services with different key values (under that key). If this is wrong, perhaps we should reconsider what a label is to GoAlert, because that doesn't really make sense to me. I do not believe we are really in the same situation as k8s since they use their labels, in my understanding, for basically one team (e.g. `app: nginx` wouldn't really work in GoAlert, as teams wouldn't care about other teams services using nginx, they would want to see only services relevant to their team or org). Perhaps I'm mistaken though.

Are you proposing that we make no changes?

**Comment by mastercactapus** [comment]
Only the prefix is intended to servce as the top-level org. For the app example, the key would be `team.name/app` since `app` by itself would be ambiguous, and only matters to `team.name`.

Kubernetes allows no-prefix labels which are meant to be user-private/defined:
> If the prefix is omitted, the label Key is presumed to be private to the user. Automated system components ... which add labels to end-user objects must specify a prefix.
> The `kubernetes.io/` and `k8s.io/` prefixes are reserved for Kubernetes core components.




If you wanted to group a bunch of services for a single team, then you could have a generic key like `TeamName` and the value would be the individual team's ID.

Using them this way gives the ability to:
- find all services with a defined `TeamName`
- find all available teams by listing the unique **values** for the `TeamName` key
- find all services owned by a specific team by looking for `TeamName=foo`.

An individual team could also make their own groupings using a prefix: `ops/PriorityGroup=P1` `ops/PriorityGroup=P2` etc.. Where the team is `ops` and they could have one or more services in the `P1` group, `P2` group and so on.

 
---

The current validation *requires* a prefix and doesn't allow underscores, we could loosen that a bit as in deployments that are single-teams it's probably a little too restrictive and makes things more confusing. If you only have one team using GoAlert, `app` is probably fine as a label. If you're in a multi-tenant environment with a lot of teams, you would want individual teams to prefix any of their own labels so they don't conflict with others.
