### ISSUE TITLE
slack/alerts: add interactivity and post updates to message

### ISSUE THREAD

**Issue by colindean** [target/goalert#19]
**Is your feature request related to a problem? Please describe:**

An alert went off. The notification went to Slack first and then to SMS and, later, voice. I acknowledged it via SMS. While I received an acknowledgment from SMS, nothing went into Slack. Someone else looked at the already-addressed problem because they didn't see the acknowledgment SMS arrive.

I got an SMS for closure, but didn't in Slack.

**Describe the solution you'd like:**

I'd like to see minimally a new Slack message saying that the issue has been acknowledged and eventually closed, one message for each event.

Adding a reaction or a message in-thread or both would reduce clutter. Updating the message would strongly indicate the status but someone could miss the edit, thus the need for a message in-thread.

Ideally, Slack's button workflow would very much work to our advantage. A button for acknowledgment when clicked does the same as acknowledging via SMS and other buttons for escalation, all-hands, manual closure, etc. could accentuate and enable a Slack-based workflow similar to other (proprietary) tools on the market.

**Describe alternatives you've considered:**

I considered highlights and manually adding the ack and closure in the thread. The text of the alert is so generic that it's risky to set something like `alert` as a highlighted word, so I've set the name of the service in the alert as a highlight. In my case, it's said rarely enough that I should not get false-positive notifications in another channel.

**Additional context:**

None pertinent right now.

**Comment by mastercactapus** [comment]
Thanks for this great write-up! I'm going to try breaking this down to make sure everyone's on the same page.

Core Problem:
- Slack channel has no way of knowing the current alert status

Proposed Features/Changes:
- In-channel buttons for ack/close/escalate
- Update in-channel message (and actions/buttons I presume) to always reflect the current status
- Publish thread/replies for status updates (escalate, ack, close, etc..)

Things that still need to be solved:
- Linking GoAlert user <-> Slack user
- How to represent & reconcile non-linked users in logs

I think we could shoot for a "phase 1" without the linking bits though:
- Thread replies would be the same as the SMS status update text (no Slack user translation)
- Update the message with current status as it changes
- Buttons/actions out of scope

Then we can get the most critical part in, and solve the linking problem separately. We'd introduce the buttons with that.

Did I miss anything?

**Comment by colindean** [comment]
You got it all 💯 . Thank you for the summarization!

**Comment by Forfold** [comment]
Hey @colindean! We have gone ahead and pulled this issue into our current sprint/[priorities](https://github.com/target/goalert/projects/3).

We're able to add interactivity to buttons and publish their responses without any issue (this is my current [WIP](https://github.com/target/goalert/tree/slack-interactivity)). We'll have to do some thinking about external updates though (i.e. the alert changing from somewhere else other than slack) for this to be considered feature complete, else we'll fall into the current workflow problem you ran into with SMS.

---

I imagine linking the alert's message thread to the alert's event log could get really noisy for some services. I think a reasonable alternative would be to:
- Include a header with the alert ID and status
- Include a footer with the last event
- Remove buttons as the status changes (i.e. don't show ack button if already ack'd)

There's a lot we can do with it- Slack uses a design system using JSON called BlockKit that can be used instead of just plaintext. This is a rough idea of what the example above would look like:

![image](https://user-images.githubusercontent.com/11381794/107266979-1ed64a00-69fb-11eb-9eff-51e0a7edcd2d.png)

I'll be sure to comment here with more info once I look more into posting impromptu message updates!

**Comment by colindean** [comment]
Looks great. 

I acknowledge that your rough idea was probably done in Slack's BlockKit designer! I'd recommend adding some colors and icons to the buttons: 👀 with yellow for Ack, ✅ with green for Close, ⬆️ with red for Escalate, and 📂 with white for Open in GoAlert.

Change the Unack to ${CURRENT_STATE} when state changes, and you're golden. 

I'll concede that I'm not actively using GoAlert on my current team presently but I think we're headed in that direction as some stuff goes to production later this year.

**Comment by Forfold** [comment]
Yep, that screenshot is just a POC from their builder- we'd definitely add in color/emojis/etc. And no worries, I think the community would benefit a lot from something like this, so I'm glad we have an issue for it! 🙂
