### ISSUE TITLE
genericapi: add additional options to createAlert handler

### ISSUE THREAD

**Issue by Forfold** [target/goalert#2532]
as of today, when using the`generic/incoming` endpoint to update an alert, the only `action` processed is to update the status of the alert to `closed` ([see here](https://github.com/target/goalert/blob/master/genericapi/handler.go#L121)). as a user, it would be useful to be able to `acknowledge` a triggered alert with this `action` key.

[initial convo in gophers slack here](https://gophers.slack.com/archives/CJQGZPYLV/p1659070094185459)

**Comment by vaishali-11** [comment]
Yes, It would be helpful if users can acknowledge alerts using genericAPI.
There are some services which sends an acknowledge signal if an alarm has been acknowledge by the system or device (like IOT devices). So, it would be helpful if an application can communicate between these type of services and alerting software to auto acknowledge using API.

I updated the generic/handler.go file with the following couple of lines of code and it works fine in my development environment.

` if action == "active" {
                status = alert.StatusActive
        }
`

**Comment by mastercactapus** [comment]
would it be possible to have the action set to close when the other service has acknowledged the issue to achieve the same purpose?

If an alert is acknowledged through the API and the upstream alert is re-triggered, no notification would come from GoAlert unless the original alert is closed and a new one is opened.

Part of the difficulty here is the generic API was designed to be a send-and-forget of an alerting state -- either it's failing (so send notifications) or it's cleared (close it). 

Having acknowledge here sort of feels like "open a silent alert" since you would no longer be sending an on-call user to GoAlert to respond (as they have already responded upstream).
