### ISSUE TITLE
Create Email Integration key from Service Details

### ISSUE THREAD

**Issue by amit-patil** [target/goalert#2631]
Hello All,

I am trying to create Email integration key from service details page. But I don't see anyway to create the same:

Steps to reproduce. Goto:
1. Services
2. Select any service, to land onto service details page.
3. Select Integration keys on right side menu
4. Select "Create New Integration Key" by clicking at bottom right.
5. Select "Type". The option to create Email Integration key is not seen.

Please advise, if Email Integration key can be created.

**Comment by mastercactapus** [comment]
Currently, to enable email integration keys you need to configure Mailgun under Admin > Config -- without that it's working as intended (not showing the unsupported type).

That being said, I think the bug is that we should always display Email as an option, but have it disabled/greyed out with a message explaining why. This is also the case for SMS and Voice for contact methods when Twilio isn't enabled.

**Comment by mastercactapus** [comment]
Since this is working as intended, closing in favor of feature request https://github.com/target/goalert/issues/3008 to improve the UI.
