### ISSUE TITLE
Alert Escalation via IVR and SMS

### ISSUE THREAD

**Issue by sivtechrepo** [target/goalert#2775]
**What problem would you like to solve? Please describe:**
Currently, GoAlert supports alert escalation via web app only and IVR/SMS doesn't have the same options for the users to escalate the issues immediately. 

**Describe the solution you'd like:**
Users need to have `escalate` alerts like ack and close alert actions in the IVR and SMS(text). 4 is used to ACK and 6 is used to Close the alert. Probably, 5 can be used to escalate the alert to the next level. For SMS(Text), 1a - ack, 1c-close and 1e-escalate alert.

**Comment by mastercactapus** [comment]
This should be doable, but there are some things we need to settle on:
1. voice options/numbers (should we plan for symmetry with a snooze option?)
2. for bundled messages (e.g. `100cc` to close all) should we also add escalation?
3. what happens if you are notified for step 1, don't respond, and have a 10 min notification rule, the alert escalates after 5 min, and then you press escalate?

For number 2, I'm thinking maybe not, as all bundled messages won't necessarily be on the same escalation step. But maybe it's more dependant on number 3

For 3, I guess we can maybe track the escalation step/number as part of the message being responded to for some (like Slack and IVR) but SMS is pretty stateless, (i.e., a single alert will have a single response code, even if it escalates).

If it's already escalated, maybe we can say "already escalated" similar to already acked/closed that way.

We used to do escalations that way, but the code as since changed so it may require some extra digging to figure out implemenation.

**Comment by dkangala** [comment]
Great idea(s)! As a suggestion, for the first iteration, I suggest to keep this enhancement simple by including the option to escalate and having Goalert call the associated member(s) in the next higher step. This would benefit all current consumers of Goalert. In future iterations, we can consider adding the additional points (1 to 3) mentioned above to further enhance the feature.
