### ISSUE TITLE
api or webhook request for on-call shifts

### ISSUE THREAD

**Issue by jjjeroenski** [target/goalert#2914]
Is there a way to get the information of who is on-call from-DT --> untill-DT with contact details for another automated system?

Possible reason could be to link this data to Twilio so they could also transfer the incoming human support phonecalls to the correct person who is on-call in that shift/period? Otherwise we need to maintain two different shedules.

Or a sheduled script/cron with an json export who could be used in Twilio or PBX
Or an api/webhook request

**Comment by mastercactapus** [comment]
On-call notifications send the list of currently on-call users from a schedule to a Slack channel. This can happen at a set time or when on-call user(s) change.

With the recent introduction of webhook support on EP steps, adding webhook support to that feature should be relatively easy.

---

Alternatively, we could expand the calendar subscription to, optionally, include all user shifts instead of only the current user.

**Comment by jjjeroenski** [comment]
Both solutions sounds good, unfortunately slack isn't very popular here in our region.
i've seen also the calendare subscription button with the export, if you're using that, you will also need to add the user or an unique userid in the output.

i guess the most flexible solution for the future is an request for shedule or shifts where you get the same output like you choose "shifts" in the webinterface.

**Comment by andrewbenington** [comment]
Webhook support added with #3036
