### ISSUE TITLE
bug: user search select not displaying exact search results

### ISSUE THREAD

**Issue by Forfold** [target/goalert#3217]
when searching for a user in a large set of usernames that are similar, there's a chance you won't see the proper user in the dropdown.

In this instance, I'll use my own name as an example, we want to search for `Nathaniel.N`

but what shows are the following users:

- Random.Nathaniel
- Random.NathanielRandom
- NathanielRand.Koch
- NathanielRand.Smith
- NathanielRand.Weeks

**Comment by mastercactapus** [comment]
Ah, I see the problem! If you look at the `search` package; The issue lies in how the search string is being split into terms and compared to the column. Since the function is splitting the string based on alphanumeric characters and ignoring other characters, searching for "Foo.F" splits into ["Foo", "F"]. The resulting regex terms ["\\mFoo", "\\mF"] will match any word starting with "Foo" and any word starting with "F", including "Foo" itself.

Here's the breakdown of the issue with one-line examples:

1. **Convert to Lowercase:** "Foo.F" becomes "foo.f".
2. **Split Search String:** "foo.f" is split into ["foo", "f"].
3. **Prepare for Prefix Matching:** Terms become ["\\mfoo", "\\mf"], enabling prefix matching.
4. **Compare Terms to Database:** In Postgres, `lower(column) ~ all(['\\mfoo', '\\mf'])` will match any column starting with "foo" and any word starting with "f", including "foo" itself.
5. **Return Matches:** Rows like "Foo.Bar" are returned because "Foo" starts with "foo" and "Foo" starts with "f".

To fix this, we'll need to find a way to ensure each term will only match separate words in the column.

**Comment by mastercactapus** [comment]
Also, this likely affects everything using `prefixSearch` which includes all list pages, not just users.

**Comment by mastercactapus** [comment]
A potential option could be to make it an ordered search (today `foo.b` will match `foo bar` and `bar foo`)

we could do that by building a regex instead of passing an array, we'll need to be careful to ensure it doesn't get too expensive though

**Comment by mastercactapus** [comment]
that way it "consumes" the matching part before moving on

**Comment by andrewbenington** [comment]
@mastercactapus enforcing order makes sense when searching for users, but would that still be desirable for other searches? e.g. should the search term "Escalation ShuttleIO" exclude the policy "ShuttleIO Escalation Policy"

**Comment by andrewbenington** [comment]
A solution for non-user searching might be to treat all terms except the last one as full words, so "Escalation Shut" would become `['\\mescalation\\M', '\\mshut']`
