### ISSUE TITLE
Error when enabling Slack

### ISSUE THREAD

**Issue by delpic** [target/goalert#33]
Hello,

We have GoAlert up and running on our Kubernetes cluster. We are trying to get Slack enabled but are getting an error when saving configuration changes. The ClientID and AccessToken are fine, so not sure why GoAlert keeps rejecting them. Attached is the screenshot of the error.

Thanks!

![Screen Shot 2019-06-25 at 4 28 04 PM](https://user-images.githubusercontent.com/929158/60131640-cf7cd080-9767-11e9-88e5-1ba70efeec08.png)

**Comment by mastercactapus** [comment]
Hmm. It could mean that Slack issues tokens of different lengths than what was originally assumed. 

For client ID GoAlert expects: `12-digits` `.` `12-digits`
For the bot access token: `xoxb-` `12-digits` `-` `12-digits` `-` `24-alphanumeric`

Make sure the AccessToken is for the bot user (check that it starts with `xoxb` and not `xoxp`).

Do the tokens you are using have different section lengths than that?

**Comment by delpic** [comment]
For clientID we have `10 digits` `.` `12 digits`

For accessToken we have `xoxp` `-` `10 digits` `-` `12 digits` `-` `12 digits` `-` `32 alphanumeric`

The accessToken is for the bot user. Thanks!

**Comment by mastercactapus** [comment]
Interesting, I wasn't aware that the numeric sections could be 10 digits. It should be easy enough to update that.

As far as the accessToken, the `xoxp` prefix indicates a [user token](https://api.slack.com/docs/token-types#user) rather than a [bot token](https://api.slack.com/docs/token-types#bot), at least according to the Slack docs.

On the OAuth & Permissions page in Slack, you should see something like this, with 2 tokens. 

![image](https://user-images.githubusercontent.com/595010/60364394-a9e00900-99ab-11e9-90df-8f04119e8d9b.png)

The bottom one should start with `xoxb` and have 4 sections instead of 5 and is the one that is needed. However, all your tokens will most likely start with the same 10-digit part so the validation will still need to be changed to allow it.
