### ISSUE TITLE
Line breaks not displaying in details section of alert details page

### ISSUE THREAD

**Issue by john-f-chamberlain** [target/goalert#3338]
**Describe the Bug:**
The details section of an alert displays the details text with line breaks stripped.

**Steps to Reproduce:**
1. Send an alert with a multi-line message in the "details" field
2. Visit the alert details page

**Expected Behavior:**
The details section should have multiple lines

**Observed Behavior:**
The details section displays all of the text on one line.

**Screenshots/Stack Traces:**
GoAlert Interface:
![image](https://github.com/target/goalert/assets/153071/1d8fdd64-f486-46da-a4b5-48f0286e6724)
Pushover:
![image](https://github.com/target/goalert/assets/153071/82937edb-d6b5-4ed6-a4b3-e0d3ce8132ae)

**Application Version:**
v0.31.1

**Additional Context:**
It appears that GoAlert is just not converting line breaks (\n) into HTML `<br>` tags.

**Comment by mastercactapus** [comment]
Details are processed as markdown text, of which the default behavior is to join subsequent lines unless there is a blank line separating.

I agree this is a bit confusing, especially because details are often sent as text without markdown processing. Testing it here on GitHub, it seems single-line breaks are also preserved.

@Forfold any idea if the markdown library we use has an option for this?

**Comment by john-f-chamberlain** [comment]
The weird thing is that if you look in page source, the line breaks are preserved, just not converted from \n to `<br>` so definitely some weird behavior from the md library. Though it should be fairly easy to do a search/replace for \n to `<br>` after the fact since the \n are still there.

**Comment by Forfold** [comment]
Looks like we can use https://github.com/remarkjs/remark-breaks as a plugin to `react-markdown`

**Comment by mastercactapus** [comment]
In our case, it's warranted -- since details are communicated in messages as rendered markdown _and_ unrendered text -- it makes sense to keep them closer together.

Plus, not all inputs to alerts are aware/capable of providing markdown anyway, so many alerts are just raw text when they come in. IMO that plugin makes a lot of sense for the UI.
