### ISSUE TITLE
proposal: remove generate from make smoketest command

### ISSUE THREAD

**Issue by Auchindoun** [target/goalert#51]
I propose we remove `make generate` from the `make smoketest` command. Running generate adds several seconds to the startup time before the smoke-tests actually run, and when running tests multiple times this can slow down development time quite a bit. Files should be generated as needed with `make generate`, in my opinion, and doesn't really fit in this scenario.

**Comment by mastercactapus** [comment]
Hmm. Yeah, we could probably have `make smoketest` depend on `install` instad of `generate` that would solve other issues too, like forgetting to run `make install` before re-running. Then things will be regenerated as-needed rather than always.

Longer-term it would be nice to do away with executing a binary entirely and just using the `app` package API now that it is an option.
