### ISSUE TITLE
100% cpu usage on goalert/all-in-one on start

### ISSUE THREAD

**Issue by freeseacher** [target/goalert#52]
**Describe the Bug:**
`docker run -it --rm -p 8081:8081 goalert/all-in-one` and one core on my laptop under linux goes 100% cpu. 

**Steps to Reproduce:**
1. just launch and nothing else
2. see htop

**Expected Behavior:**
Launched app should not use cpu until get job to do

`
$ docker run -it --rm -p 8081:8081 goalert/all-in-one
Digest: sha256:a8559ab79aa5dc56a14d87769cd2318bcca0eba71bd76c0916c5f3230fb2505`

**Desktop:**
 - OS: mint 19.1]

**Additional Context:**
I wish i have much more info to provide but no idea what can i add.
BTW: That's a good start! Can't wait to find the time to dive into the details.

**Comment by mastercactapus** [comment]
Interesting. I think what could be happening is that, since the demo data was generated awhile ago, when it starts up it's working to "catch-up" with all the time that has passed. (i.e. processing rotations, escalations, schedules, etc...)

It should eventually settle though once it works through the backlog if that's the case, can you confirm that?

We'll still need to come up with a way to keep the init data current for the demo container, or at least update the timestamps. Also probably a good opportunity to do some profiling to see if we can make it more efficient when there's a giant backlog of work. :)

**Comment by mastercactapus** [comment]
The `all-in-one` container has been updated for the latest release with this issue resolved.

To prevent it in the future, time-sensitive data (like rotation start times) has been omitted from `init.sql` -- meaning it will use the current timestamp at first-run/insert thus not getting "behind".

There will always be a first-time cost due to processing the random schedules, rotations, etc.. in the container but the growing backlog issue should be fixed.

If you're still seeing this with the latest tag, feel free to a leave a comment and we can re-open.
