### ISSUE TITLE
Unable to set day of week for handoff

### ISSUE THREAD

**Issue by prestonvanloon** [target/goalert#553]
**Describe the Bug:**

In the rotations, we see this 

![Screenshot from 2020-03-28 15-35-24](https://user-images.githubusercontent.com/7246818/77835439-c7dcc480-7109-11ea-976e-f897bfd515da.png)

Then when we try to set the hand off date on the rotation, we keep getting NaN / unset week day. 

![Screenshot from 2020-03-28 15-36-20](https://user-images.githubusercontent.com/7246818/77835449-e773ed00-7109-11ea-94fd-281aa6142280.png)

Looking at the console, we see NaN instead of the expected integer value for week day.

**Steps to Reproduce:**
See above. We try to set the day of week on an existing rotation.

**Expected Behavior:**
Sets week day.

**Observed Behavior:**
See above.

**Screenshots/Stack Traces:**
See above.

**Application Version:**

v0.24.1

**Comment by mastercactapus** [comment]
Try setting your time zone to `America/Los_Angeles`

`PST8PDT` (as well as `US/Pacific` and quite a few others in the list) are deprecated but still displayed (known issue).

Basically the backend/DB still supports them fine, as they are just aliased, but web browsers have since removed support for the older names, causing the UI to break when one is selected.

**Comment by prestonvanloon** [comment]
I think that was the problem. I ended up deleting everything and starting over and it’s working now with Los Angeles time zone. Thanks
