### ISSUE TITLE
Specify Rotation Start Date

### ISSUE THREAD

**Issue by jghibiki** [target/goalert#993]
**Is your feature request related to a problem? Please describe:**
While setting up a new 4 day rotation for our team, after the change the person "on call" is listed as having 2days, x hours, and y minutes left instead of 4days - (time since midnight today). This was surprising to me as i expected the rotation to start relative to today (when i made the change) instead of relative to some other unknown date time.

**Describe the solution you'd like:**
It would be useful to be able to set the "zero day" of the rotation. i.e. when calculating how much time until the next rotation, allow a user to set the "zero day" in that calculation. Currently it is unclear how that date is determined.

Example:
For an existing support rotation, i modify the rotation period to be 4 days, and i have 3 people in the rotation (A, B, C). 
Currently the rotation that is generated will look like so:
- A : 2 days x hours y minutes left 
- B: Starts at 12:00 am in 3 days
- C: Starts at 12:00 am in 5 days

It is unclear what date the remaining time the calculation is based on (what i am referring to as the "zero day" of the rotation.

My suggestion is that when changing the rotation period, you give the option to select a date for the rotation calculations to start relative to, or simply a checkbox to reset it to be relative to today at the "handoff time" (or another time such as midnight for cases where "handoff time" today will occur after the change is made). 
Example:
For an existing support rotation, i modify the rotation period to be 4 days, and i have 3 people in the rotation (A, B, C). I select the "zero day" of the rotation to be today.
Currently the rotation that is generated will look like so:
- A : 3 days x hours y minutes left 
- B: Starts at 12:00 am in 5 days
- C: Starts at 12:00 am in 7 days

All of the generated count downs are calculated relative to `(today at the handoff time) + (elapsed time since then) - 4 days`

**Describe alternatives you've considered:**
As mentioned above the "zero day" reset could be made:
- as a simple checkbox and set to the most recent handoff to when the rotation schedule edit is made
- a date picker to set the relative date (may be useful for fixing rotations that were set up improperly by accident)

**Additional context:**
Not that i can think of.

**Comment by mastercactapus** [comment]
I think we may be able to do one better, instead of changing/setting the relative date and guiding the user through how it works under the covers, we can allow the user to select the "next handoff time" as a timestamp directly. We can make the code do the work of figuring out any "relative" time behind the scenes.

Based on this description of the problem, as well as other comments when this has come up in the past, the goal is almost always down to "I want/expect the next handoff time to be exactly X" -- so we can just make that the experience outright.

The current flow works fairly well for this -- as long as the rotation is a single day/week. But beyond that, saying "Wednesday at 8AM" is ambiguous if, for example, it is a 2 week rotation.

Changing the field to allow "Wednesday Nov. 18th, at 8AM" would solve both use cases.

Additionally, we could put some hint text under the input field indicating something like "The following handoff will be Dec. 2nd" for further hint/clarification. This might also help in cases where a user is configuring a rotation handoff close to the current time (e.g. set the handoff to 9:00AM when it's 9:05AM -- we can relax the need for it to be strictly in the future)

Implementation notes:
- For existing rotations, we can use the calculated next-handoff time as the edit value
- We can save the new handoff as the rotation "start" parameter (even if in the future)
- For new rotations, just adjust the default "start" value to be in the future, rather than "most recent" in the create dialog

**Comment by jghibiki** [comment]
> I think we may be able to do one better, instead of changing/setting the relative date and guiding the user through how it works under the covers, we can allow the user to select the "next handoff time" as a timestamp directly. We can make the code do the work of figuring out any "relative" time behind the scenes.

This sounds great to me, the only special case I can think of that may be helpful, would be the ability to set "next handoff time" as a date+time in the past, this might be good for correcting a mis-configured rotation. e.g. If i was supposed to be primary today, but my college set up the rotation incorrectly several days ago, I can go in and correct the rotation start time to this past midnight (today at 00:00:00). Not sure if this would jive with your implementation though.

**Comment by mastercactapus** [comment]
It will definitely allow for that, the "next handoff" can actually be any point in time past or future.

We plan to include a little note that will display the next 3 or so future handoff times based on that reference time.

**Comment by jghibiki** [comment]
Yeah, I saw the screenshot in your PR. That looks perfect, thanks!
